
DROP DATABASE IF EXISTS Final_Exam_JavaCORE;
CREATE DATABASE Final_Exam_JavaCORE;
USE	Final_Exam_JavaCORE;

-- CREATE TABLE: User
-- CREATE TABLE `User` (
-- id			TINYINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
-- FullName	VARCHAR (20) CHECK (LENGTH(FullName)>=6),
-- Email		VARCHAR (20) UNIQUE KEY NULL,
-- `Password`	VARCHAR (20) UNIQUE KEY NULL,
-- `Role`		Enum	('Manager','Employee') default NULL
-- );
-- CREATE TABLE: Manager
CREATE TABLE Manager (
idManager	TINYINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
FullName	VARCHAR (20) CHECK (LENGTH(FullName)>=6),
Email		VARCHAR (20) UNIQUE KEY NULL,
`Password`	VARCHAR (20) UNIQUE KEY NULL,
ExpInYear	TINYINT UNSIGNED
);

-- CREATE TABLE: Employee
CREATE TABLE Employee (
idEmployees	TINYINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
FullName	VARCHAR (20) CHECK (LENGTH(FullName)>=6),
Email		VARCHAR (20) UNIQUE KEY NULL,
`Password`	VARCHAR (20) UNIQUE KEY NULL,
projectId	TINYINT UNSIGNED,
ProSkill	VARCHAR (20)
);

-- CREATE TABLE: Project
CREATE TABLE Project (
projectId	TINYINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
teamSizes	INT UNSIGNED,
idManager	TINYINT UNSIGNED,
idEmployees	TINYINT UNSIGNED,
FOREIGN KEY (idManager) REFERENCES Manager (idManager) ON DELETE CASCADE,
FOREIGN KEY (idEmployees) REFERENCES Employee (idEmployees) ON DELETE CASCADE
);
-- alter table Employee add foreign key (projectId) references Project(projectId);
