
/*-- Requirement 1--*/
/*-- Questions --*/
-- 1. Tạo table với các ràng buộc và kiểu dữ liệu .Thêm ít nhất 5 bản ghi vào table.
DROP DATABASE IF EXISTS Testing_Exam_1;
CREATE DATABASE Testing_Exam_1;
USE	Testing_Exam_1;

-- CREATE TABLE CUSTOMER:
CREATE TABLE 	Customer (
CustomerID		TINYINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
CustomerName	NVARCHAR(50),
PhoneNumber		CHAR(12) NOT NULL,
Email			VARCHAR (30) UNIQUE KEY DEFAULT ('KHONG CO MAIL'),
Address			VARCHAR	(50) DEFAULT ('Chua Update'),
Note			VARCHAR	(100)
);

-- CREATE TABLE CAR:
CREATE	TABLE	Car (
CarID			TINYINT UNSIGNED PRIMARY KEY,
Maker			ENUM ('HONDA', 'TOYOTA', 'NISSAN') NOT NULL,
Model			VARCHAR (50) UNIQUE KEY,
`Year`			INT UNSIGNED,
Car_Color		VARCHAR (50),
Note			VARCHAR	(200)
);

-- CREATE TABLE CAR_ORDER
CREATE TABLE Car_Oder (
OrderID			TINYINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
CustomerID		TINYINT UNSIGNED DEFAULT (0),
CarID			TINYINT UNSIGNED,
Amount			TINYINT UNSIGNED DEFAULT (1),
SalePrice		INT	UNSIGNED DEFAULT (0),
OrderDate		DATETIME DEFAULT NOW(),
DeliveryDate	DATETIME DEFAULT NOW(),
DeliveryAddress	VARCHAR (100),
`Status`		ENUM ('0','1','2'),
Note			VARCHAR	(200),
FOREIGN KEY (CustomerID) REFERENCES Customer (CustomerID),
FOREIGN KEY (CarID) REFERENCES Car (CarID)
);
