
DROP DATABASE IF EXISTS Final_Exam_2;
CREATE DATABASE Final_Exam_2;
USE	Final_Exam_2;

-- CREATE TABLE: GiangVien	
CREATE TABLE GiangVien (
GiangVien_ID	TINYINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
GiangVien_NAME	VARCHAR (20) UNIQUE KEY,
Luong			INT UNSIGNED	
);

-- CREATE TABLE: SinhVien	
CREATE TABLE SinhVien (
SinhVien_ID		TINYINT UNSIGNED PRIMARY KEY,
SinhVien_NAME	VARCHAR (20) UNIQUE KEY,
Namsinh			INT UNSIGNED,	
Quequan			VARCHAR (20)	
);

-- CREATE TABLE: DeTai	
CREATE TABLE DeTai (
DeTai_ID		TINYINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
DeTai_NAME		VARCHAR (100) UNIQUE KEY,
Kinhphi			INT UNSIGNED,	
NoiThucTap		VARCHAR (20)	
);

-- CREATE TABLE: HuongDan	
CREATE TABLE HuongDan (
HuongDan_ID		TINYINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
SinhVien_ID		TINYINT UNSIGNED,
DeTai_ID		TINYINT UNSIGNED,
GiangVien_ID	TINYINT UNSIGNED,
ketqua			VARCHAR (20),
FOREIGN KEY	(SinhVien_ID) REFERENCES SinhVien (SinhVien_ID),
FOREIGN KEY	(DeTai_ID) REFERENCES DeTai (DeTai_ID),
FOREIGN KEY	(GiangVien_ID) REFERENCES GiangVien (GiangVien_ID)
);
